
server:
  servlet:
    context-path: "/wolf_manage"
spring:
  application:
  name: WolfManage
  datasource:
    url: jdbc:mysql://localhost:3306/db_wolf_manage?createdIfNoteExit=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    password: admin
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
